const DEFAULT_ACTOR_IMAGES = {
	character: "systems/grimwild-action/assets/actors/character.webp",
	monster: "systems/grimwild-action/assets/actors/monster.webp",
	linkedChallenge: "systems/grimwild-action/assets/actors/challenge.webp",
	battleground: "systems/grimwild-action/assets/actors/battleground.webp",
	faction: "systems/grimwild-action/assets/actors/faction.webp",
	party: "systems/grimwild-action/assets/actors/party.webp",
	storykit: "systems/grimwild-action/assets/actors/storykit.webp"
};

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class GrimwildActor extends Actor {
	/**
	 * Provide default actor and token artwork per actor type.
	 * @param {object} data Source data being created.
	 * @returns {{img: string, prototypeToken: object}}
	 */
	static getDefaultArtwork(data) {
		const img = DEFAULT_ACTOR_IMAGES[data?.type] ?? "icons/svg/mystery-man.svg";
		return {
			img,
			prototypeToken: {
				texture: { src: img }
			}
		};
	}

	/** @override */
	prepareData() {
		// Prepare data for the actor. Calling the super version of this executes
		// the following, in order: data reset (to clear active effects),
		// prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
		// prepareDerivedData().
		super.prepareData();
	}

	/** @override */
	prepareBaseData() {
		// Data modifications in this step occur before processing embedded
		// documents or derived data.
	}

	/**
	 * @override
	 * Augment the actor source data with additional dynamic data that isn't
	 * handled by the actor's DataModel. Data calculated in this step should be
	 * available both inside and outside of character sheets (such as if an actor
	 * is queried and has a roll executed directly from it).
	 */
	prepareDerivedData() {
		// const actorData = this;
		// const flags = actorData.flags.grimwild || {};
	}

	/**
	 *
	 * @override
	 * Augment the actor's default getRollData() method by appending the data object
	 * generated by the its DataModel's getRollData(), or null. This polymorphic
	 * approach is useful when you have actors & items that share a parent Document,
	 * but have slightly different data preparation needs.
	 */
	getRollData() {
		return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
	}

	/**
	 * Operations on actor creation.
	 *
	 * @inheritdoc
	 */
	async _preCreate(data, options, user) {
		const defaults = this.constructor.getDefaultArtwork(data);
		const updateData = {};

		if (!data.img && defaults?.img) {
			updateData.img = defaults.img;
		}

		// Start with the default prototype token (sets texture src), then merge in existing data.
		let prototypeToken = foundry.utils.mergeObject(
			defaults?.prototypeToken ?? {},
			data.prototypeToken ?? {},
			{ inplace: false }
		);

		// Preserve existing character token defaults.
		if (this.type === "character") {
			prototypeToken = foundry.utils.mergeObject(
				prototypeToken,
				{
					actorLink: true,
					disposition: 1, // friendly
					sight: { enabled: true }
				},
				{ inplace: false }
			);
		}

		if (Object.keys(prototypeToken).length) {
			updateData.prototypeToken = prototypeToken;
		}

		if (Object.keys(updateData).length) {
			this.updateSource(updateData);
		}
	}

	/**
	 * Prevent empty item payloads from wiping owned items (e.g., form submits with no item data).
	 *
	 * @override
	 */
	async _preUpdate(changes, options, user) {
		await super._preUpdate(changes, options, user);

		const incomingItems = changes?.items;
		const hasItems = this.items?.size > 0;
		const itemsEmpty = Array.isArray(incomingItems)
			? incomingItems.length === 0
			: incomingItems && foundry.utils.isEmpty(incomingItems);

		if (hasItems && itemsEmpty) {
			delete changes.items;
		}
	}
}
